name: Go Format Check

on: [push, pull_request]

jobs:
  format-check:
    name: Check Go Format
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.14'
        
    - name: Check if Go files are formatted
      run: |
        # Run go fmt and capture any files that would be changed
        unformatted=$(go fmt ./...)
        if [ -n "$unformatted" ]; then
          echo "The following files are not properly formatted:"
          echo "$unformatted"
          echo ""
          echo "Please run 'go fmt ./...' to format your code."
          exit 1
        fi
        echo "All Go files are properly formatted!"
        
    - name: Verify no formatting changes needed
      run: |
        # Alternative approach: check if running go fmt would make any changes
        if [ -n "$(gofmt -l .)" ]; then
          echo "The following files need formatting:"
          gofmt -l .
          echo ""
          echo "Please run 'go fmt ./...' or 'gofmt -w .' to format your code."
          exit 1
        fi
        echo "All files pass go fmt check!"